steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - build
      - -f
      - chatai/Dockerfile
      - -t
      - southamerica-west1-docker.pkg.dev/integraciones-484915/integraciones/chatai:latest
      - .

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - run
      - deploy
      - chatai
      - --image=southamerica-west1-docker.pkg.dev/integraciones-484915/integraciones/chatai:latest
      - --region=southamerica-west1
      - --project=integraciones-484915
      - --platform=managed

images:
  - southamerica-west1-docker.pkg.dev/integraciones-484915/integraciones/chatai:latest
